### ISSUE TITLE
Small error w/ time data format

### ISSUE THREAD

**Issue by Paulie420** [JeffJetton/retrofeed#1]
ValueError: time data '2023 13 Feb 6:53 pm CST' does not match format '%Y %d %b %I:%M %p %Z'

I ran the .py once, and it worked - but every time after I get the above... will dig in a bit - this is awesome, I'm just starting to play around with it. Thanks!!

**Comment by JeffJetton** [comment]
Thanks for the issue. I'm assuming that's when fetching weather info? That particular string parses fine with that format string when I try it directly in Python:

`print(dt.datetime.strptime('2023 13 Feb 6:53 pm CST', '%Y %d %b %I:%M %p %Z'))`

I wonder if it's some sort of localization setting on your particular computer that's different? Let me know what you find out! In any case, error-handling could definitely be better in this program, that's for sure.

**Comment by JeffJetton** [comment]
@Paulie420 sounds like changing the lat/lon fixed it for you. Not sure why that would make a difference, but glad it's working for you.
