### ISSUE TITLE
Install and Launch instructions

### ISSUE THREAD

**Issue by mattmurf** [JeffJetton/retrofeed#2]
I'm working on getting this to work on a P Zero-W using Raspbian Lite and wanted to capture issues and approach.

I'm currently stuck on how to run the scripts.  I changed the permissions to allow to 711 but am stuck from there.

Here's the instructions I have so far.

To make troubleshooting easier, I'm working an approach that connects to an HDMI monitor fist, get it working and then connect to an analog display once the basics are working.  I expect there may be many who would like to get this running but don't have an analog display available.  

Download and open Raspberry Pi Imager to Windows desktop to provision microSD card with OS
- Insert MicroSD Card
- Click the Operating System button to select an OS
-  Select Raspberry PI OS Lite (32-bit)
- Click on Storage Button to select the MicroSD  
- Configure System Settings via the Imager GUI Settings button
- Set the hostname
- Enable SSH
- Set Username and Password
- Configure WIFI (only supports DHCP)

Plug in a monitor and keyboard or connect via SSH
Log In

Update the OS and Install Git
- Sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install git
- git clone https://github.com/jeffjetton/retrofeed
- cd retrofeed
- chmod 711 *.py //Change permissions so the scripts run

**Comment by JeffJetton** [comment]
These are Python scripts rather than shell scripts, so you can skip the chmod step. Then just tell Python to run the main script:

`python retrofeed.py`

**Comment by mattmurf** [comment]
Thanks!  That was just stupidity on my part.  I'll keep editing the initial question as I run into things with the fixes.  Hopefully this will help someone else.

**Comment by JeffJetton** [comment]
Thank you for putting these instructions together!
