### ISSUE TITLE
ap_news.py formatting changed??

### ISSUE THREAD

**Issue by Paulie420** [JeffJetton/retrofeed#5]
My ap_news.py only returns "NEWSFEED UNAVAILABLE". I've been debugging and apnews.com doesn't seem to return text with the old "headline:" and other prompts ap_news.py looks for...

Has anyone fixed this on their own yet??? Or, should I post my current [failed] attempts:

```
changed ./segments/spot-the-station.py;
#LINE 70 changed to:
-----
# Assuming the input is always "{ts '...'}"
date_string_clean = date_string[5:-2]
date_time = dt.datetime.strptime(date_string_clean, '%Y-%m-%d %H:%M:%S') - utc_diff
-----

added to debug lines to ./segments/ap_news.py;
#LINE 86 - #Comment out when done!!!
-----
        #DEBUGGING:
with open("debug.txt", "w", encoding="utf-8") as f:
    f.write(str(response.status_code) + "\n")
    f.write(response.text[:1000] + "\n\n")
    f.write(response.text)
-----

changed get_headlines function in ./segments/ap_news.py;
-----
def get_headline(self, s):
    pos_start = s.find('<a class="Link "')
    if pos_start < 0:
        return None
    pos_start = s.find('>', pos_start) + 1  # Find the next '>' after the start position
    pos_end = s.find('</a>', pos_start)     # Find the closing tag '</a>'
    if pos_end < 0:
        return None
    headline = s[pos_start:pos_end]
    return self.d.strip_tags(self.d.clean_chars(headline))
-----
changed code in ./segments/ap_news.py;
-----
                #if headline is not None and summary is not None and headline.lower().find('top stories ') < 0:
                    #self.data['items'].append({'headline':headline, 'summary':summary})
                    if headline is not None and headline.lower().find('top stories ') < 0:
                        if summary is None:
                            summary = "Summary not available."
                        self.data['items'].append({'headline':headline, 'summary':summary})
-----
ap_news.py is still broke - but we did fix the spot-the..py. 
reinstalled original ap_news.py - must fix later.
```

**Comment by JeffJetton** [comment]
Hi Paulie420! Yes, the apnews website has changed their format and the current version here on github doesn't recognize it.

But, I've totally rewritten this whole thing to make everything more modular/flexible. Haven't pushed it to GitHub yet because I wanted to fix this AP problem while I was at it. Hang tight! :-)

**Comment by Paulie420** [comment]
I'm close to a fix, too - I'm SURE I don't code as well as you, but if I get it working perfectly I can share too - HOWEVER, I'm in no rush so its nice to hear that you're still thinking about this weird script!! :P

I modified a bit, too, to set the font in-console so I can just use it on any RPi - even w/o RCA connection. Just set the terminal to a 40-column friendly font... anyway, love Retroterm - wonder what else I can add.

**Comment by JeffJetton** [comment]
Okay, I've pretty much totally redone the wp_news.py module. It's working fine for me now on Raspberry Pi OS (Debian) and Mac OS. (Note that the whole project now requires Python 3.11 or higher.)
